# Auto-generated by `scripturegraph scheduler install`.
$ErrorActionPreference = "Continue"
$log = "C:\Users\jacer\repos\SCRIPTURE GRAPH\Scripture Graph\.scripture-engine\logs\scheduler-weekly.log"
if ((Test-Path $log) -and ((Get-Item $log).Length -gt 5MB)) {
    Move-Item -Force $log "$log.old"
}
"=== weekly run started $(Get-Date -Format o) ===" | Out-File -Append -Encoding utf8 $log
& "C:\Users\jacer\repos\SCRIPTURE GRAPH\.venv\Scripts\python.exe" -m scripturegraph --root "C:\Users\jacer\repos\SCRIPTURE GRAPH" run --weekly *>> $log
"=== finished $(Get-Date -Format o) (exit $LASTEXITCODE) ===" | Out-File -Append -Encoding utf8 $log
