"""Windows Task Scheduler integration (the OUTER clock only).

Three current-user tasks run thin PowerShell wrappers that invoke the
deterministic Python orchestrator. No AI product's scheduler is the root.
Enable/disable without uninstalling via config (automation.enabled) or
`schtasks /Change /TN <task> /DISABLE`.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from scripturegraph.context import Ctx

_CREATE_NO_WINDOW = 0x08000000

TASKS = {
    "study": "ScriptureGraph Study",
    "frequent": "ScriptureGraph Frequent",
    "nightly": "ScriptureGraph Nightly",
    "weekly": "ScriptureGraph Weekly",
}


def _venv_python(ctx: Ctx) -> str:
    cand = ctx.root / ".venv" / "Scripts" / "python.exe"
    return str(cand) if cand.exists() else sys.executable


def _script_path(ctx: Ctx, kind: str) -> Path:
    return ctx.root / "scripts" / f"run-{kind}.ps1"


def write_runner_scripts(ctx: Ctx) -> list[Path]:
    (ctx.root / "scripts").mkdir(exist_ok=True)
    out = []
    for kind in TASKS:
        script = _script_path(ctx, kind)
        log = ctx.logs_dir / f"scheduler-{kind}.log"
        content = f"""# Auto-generated by `scripturegraph scheduler install`.
$ErrorActionPreference = "Continue"
$log = "{log}"
if ((Test-Path $log) -and ((Get-Item $log).Length -gt 5MB)) {{
    Move-Item -Force $log "$log.old"
}}
"=== {kind} run started $(Get-Date -Format o) ===" | Out-File -Append -Encoding utf8 $log
& "{_venv_python(ctx)}" -m scripturegraph --root "{ctx.root}" run --{kind} *>> $log
"=== finished $(Get-Date -Format o) (exit $LASTEXITCODE) ===" | Out-File -Append -Encoding utf8 $log
"""
        script.write_text(content, encoding="utf-8")
        out.append(script)
    return out


def _schtasks(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(["schtasks", *args], capture_output=True, text=True,
                          creationflags=_CREATE_NO_WINDOW, timeout=60)


def _ps_wrapper(script: Path) -> str:
    return (f'powershell.exe -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden '
            f'-File "{script}"')


def _apply_power_settings(task_name: str) -> bool:
    """schtasks cannot set battery behavior; by default tasks refuse to start
    on battery and are KILLED when the machine unplugs (which orphans the
    engine process). Patch the settings via PowerShell: run on battery, never
    stop on power transitions, catch up missed starts, 12h hard limit."""
    ps = (
        "$s = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries "
        "-DontStopIfGoingOnBatteries -StartWhenAvailable "
        "-ExecutionTimeLimit (New-TimeSpan -Hours 12); "
        f"Set-ScheduledTask -TaskName '{task_name}' -Settings $s | Out-Null")
    cp = subprocess.run(
        ["powershell.exe", "-NoProfile", "-NonInteractive", "-Command", ps],
        capture_output=True, text=True, creationflags=_CREATE_NO_WINDOW, timeout=60)
    return cp.returncode == 0


def install(ctx: Ctx) -> dict:
    write_runner_scripts(ctx)
    sched = ctx.cfg.get("scheduler", {})
    specs = {
        "study": ["/SC", "MINUTE", "/MO", str(sched.get("study_minutes", 30))],
        "frequent": ["/SC", "HOURLY", "/MO", str(sched.get("frequent_hours", 2))],
        "nightly": ["/SC", "DAILY", "/ST", str(sched.get("nightly_time", "02:30"))],
        "weekly": ["/SC", "WEEKLY", "/D", str(sched.get("weekly_day", "SUN")),
                   "/ST", str(sched.get("weekly_time", "03:30"))],
    }
    results = {}
    for kind, task_name in TASKS.items():
        cp = _schtasks("/Create", "/F", "/TN", task_name,
                       "/TR", _ps_wrapper(_script_path(ctx, kind)), *specs[kind])
        ok = cp.returncode == 0
        power_ok = _apply_power_settings(task_name) if ok else False
        results[task_name] = ("installed" if ok else f"FAILED: {cp.stderr.strip()[:200]}") \
            + ("" if power_ok or not ok else " (power settings NOT applied)")
        ctx.log.info("scheduler.install", task=task_name, ok=ok, power_settings=power_ok)
    return results


def remove(ctx: Ctx) -> dict:
    results = {}
    for task_name in TASKS.values():
        cp = _schtasks("/Delete", "/F", "/TN", task_name)
        results[task_name] = "removed" if cp.returncode == 0 else "not present"
    ctx.log.info("scheduler.remove", **{k.split()[-1]: v for k, v in results.items()})
    return results


def status(ctx: Ctx) -> dict:
    results = {}
    for task_name in TASKS.values():
        cp = _schtasks("/Query", "/TN", task_name, "/FO", "LIST")
        if cp.returncode != 0:
            results[task_name] = "not installed"
        else:
            info = {}
            for line in cp.stdout.splitlines():
                if ":" in line:
                    k, _, v = line.partition(":")
                    if k.strip() in ("Status", "Next Run Time", "Last Run Time",
                                     "Last Result"):
                        info[k.strip()] = v.strip()
            results[task_name] = info or "installed"
    return results
